### ISSUE TITLE
Question: Class level hierarchy in the the results reported by TestNG

### ISSUE THREAD

**Issue by arunkumar-muthusamy** [reportportal/example-java-TestNG#12]
Hi,

I ran this sample project using logback with more than 1 TestNG class under the test. But in the report portal, Class level information is not reported which makes the results looks jumbled/not readable.

1. Here is the xml given the project example. Results in RP looks good because, we have only one Class per test occurrence. 
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Logging Tests" parallel="classes" thread-count="10">
    <listeners>
        <listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"/>
    </listeners>
    <test verbose="1" name="Lucky Pug">
        <classes>
            <class name="com.epam.rp.tests.logging.LuckyPugTest"/>
        </classes>
    </test>

    <test verbose="1" name="XML logging">
        <classes>
            <class name="com.epam.rp.tests.logging.XmlLoggingTest"/>
        </classes>
    </test>

    <test verbose="1" name="Better XML logging">
        <classes>
            <class name="com.epam.rp.tests.logging.XmlLoggingBetterTest"/>
        </classes>
    </test>

    <test verbose="1" name="Json logging">
        <classes>
            <class name="com.epam.rp.tests.logging.JsonLoggingTest"/>
        </classes>
    </test>

    <test verbose="1" name="File logging">
        <classes>
            <class name="com.epam.rp.tests.logging.LoggingTest"/>
        </classes>
    </test>

</suite>
```
![image](https://user-images.githubusercontent.com/47788194/55023432-27723280-4fd3-11e9-824d-be6e21a0a67b.png)

2. Running with multiple class on a test.

```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Logging Tests Suite" parallel="classes" thread-count="10">
    <listeners>
        <listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"/>
    </listeners>
    <test thread-count="5" name="Test" parallel="classes">
        <classes>
            <class name="com.epam.rp.tests.logging.LuckyPugTest"/>
            <class name="com.epam.rp.tests.logging.XmlLoggingTest"/>
            <class name="com.epam.rp.tests.logging.XmlLoggingBetterTest"/>
            <class name="com.epam.rp.tests.logging.JsonLoggingTest"/>
            <class name="com.epam.rp.tests.logging.LoggingTest"/>
        </classes>
    </test>
</suite>
```
![image](https://user-images.githubusercontent.com/47788194/55023530-5be5ee80-4fd3-11e9-9e0a-bf1b3fface44.png)

As you could see, the test methods are jumbled and also, we have no way to trace it back to the Class it belongs to.

**RP Build: 4.3.6**

Appreciate any input!

**Comment by arunkumar-muthusamy** [comment]
Digged the RP TestNG Listener interface, it looks "com.epam.reportportal.testng.ITestNGService" does not have implementation for this use case. Did anyone fced similar situation & how did we solved it?

**Comment by DzmitryHumianiuk** [comment]
@arunkumar-muthusamy are you looking for representation of test name as:
`com.epam.rp.tests.logging.LuckyPugTest.logjsonBase64`

or represent additional suite level, which will replicate mentioned TestClass?

**Comment by arunkumar-muthusamy** [comment]
@DzmitryHumianiuk that could solve the issue to some extent. But still we will get methods listed from different test class in one flat list (we may end up sort the results & filter it). 

My ask/suggestion is can we introduce a hierarchy for Class?

Launch > Suite > Test > **TestClass** > TestMethod(s)

**Comment by DzmitryHumianiuk** [comment]
@arunkumar-muthusamy 

Object in RP:
`Launch > Suite > Test > Step`
are equal in TestNG to
`Launch > Suite > TestClass > TestMethod`

it's kind of not-that-obvious implementation, but we were try to meet BDD with it.

the hierarchy you mentioned, it will look like
`Launch > Suite > Suite > Test > TestMethod(s)`

we plan to make it more plain.
In 5.0 we will introduce Steps, which will be just a step in test. And will have no statistics.
after it, we plan to remove any name and logic links to object.
All object will be TestItems. The only difference will be parameter as `hasStat`, send from agent.

So mapping to objects in TestNG will be done via property file.
like
```
Suite == TestItem, label="Suite", hasStat=false
TestClass == TestItem, label="TestClass", hasStat=false
Test == TestItem, label="Test", hasStat=true
Step == TestItem, label="TestClass", hasStat=false
```

**Comment by arunkumar-muthusamy** [comment]
Excellent! Sounds cool @DzmitryHumianiuk. Thank you!

**Comment by DzmitryHumianiuk** [comment]
@arunkumar-muthusamy the situation mentioned by you happens just because there is no proper handler for it.
and should be addressed in https://github.com/reportportal/agent-java-testNG/blob/master/src/main/java/com/epam/reportportal/testng/TestNGService.java 
in case if it possible at all.

The current behavior is due to the specifics of how execution order formed by TestNG.
RP is wired on internal event of TestNG.

And in case#1, we can see that it fires event of started Class for each of `<classes>..</classes>` initialization.
In case#2, it fires this event only once, for `<classes>..</classes>` initialization as well.

As i see, this should be updated in testNG first, otherwise we will have a greatest-dirty-workaround-ever.

Or just change the way, who we report results.
This is fundamental.
If we will ignore suites and structure of TestNG object, and just represent structure, which is represented by test code structure itself.

**Comment by arunkumar-muthusamy** [comment]
@DzmitryHumianiuk agree with you. I try to extend you service class and try to customize it, it looked pretty ugly. 

The solution which i have implemented is, I created a custom Lister by extending IAlterSuiteListener and restructure my TestNG.xml in such a way it will get long with reportportal.

**Comment by DzmitryHumianiuk** [comment]
@arunkumar-muthusamy that's the right way!

**Comment by omkarnathsingh** [comment]
@arunkumar-muthusamy Can you please share your solution? I am facing similar issue. Or is there a way to remove these suite level loggings?

**Comment by arunkumar-muthusamy** [comment]
> @arunkumar-muthusamy Can you please share your solution? I am facing similar issue. Or is there a way to remove these suite level loggings?

Hi,

Typically TestNG pulls multiple TestClass under Test occurrence, while we use method selectors or groups to run tests. Please use TestNG listener (IAlterSuite) and restructure your TestNG suite.xml (during runtime) by stacking one test class per test occurrence.

Or if you are creating TestNG-Suite.xml manually, then organize it in such a way that it has one test class per test occurrence.

**Comment by omkarnathsingh** [comment]
Thanks @arunkumar-muthusamy for input. I will try that way,
