### ISSUE TITLE
Multiple launches getting generated in RP for single execution

### ISSUE THREAD

**Issue by KunalShokeen432** [reportportal/example-java-TestNG#19]
Hi All,

I have setup  a simple Maven + TestNG + RP project.I have followed the steps mentioned in this rep o for TestNg integration.

The launches are getting pushed to RP successfully ,however for single suite execution there are 2 launches in RP.

My testng.xml also does not contain multiple suites i.e :

<!DOCTYPE suite SYSTEM "http://beust.com/testng/testng-1.0.dtd" >
<suite name="My Test Suite">
    <listeners>
		<listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener" />
    </listeners>
    <test name="My Test Testname">
        <classes>
            <class name="com.sapient.tests.MyTests"/>
        </classes>
    </test>
</suite>

The strange part is the latest launch is always in progress and have no data inside and the first launch is executed successfully with data.

PFB screesnhot of RP 👍 

![image](https://user-images.githubusercontent.com/32562642/61000661-89d12200-a37b-11e9-8cb1-e8601bc0753e.png)

Can anyone please help me with why multiple launches in RP for single suite execution.

**Comment by ishanm120** [comment]
I was also facing the same issue.
It got fixed after updating testNG version to 6.11

**Comment by HardNorth** [comment]
@KunalShokeen432 Maven actually can fork Processes, so each suite will be in a separate JVM. We are trying to implement a logic which will join such launches into one, but it's still in progress. Currently for V4 agents it's generally recommended to not use process forks.
